BH_DJANGO/BH_DJANGO/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from pages import views

urlpatterns = [
    path('viv_help/', views.viv_help_view, name='viv_help'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('viv/', views.viv_view, name='viv'),
    path('flash/', views.flash_view, name='flash'),
    path('unsub/', views.unsub_view, name='unsub'),
    path('recent_admissions/', views.recent_admissions_view, name='recent_admissions'),
    path('loc/', views.loc_view, name='loc'),
    path('gender/', views.gender_view, name='gender'),
    path('doc/', views.doc_view, name='doc'),
    path('age/', views.age_view, name='age'),
    path('caseload/', views.caseload_view, name='caseload'),
    path('', views.homepage_view, name='home'),
    path('admin/', admin.site.urls),
    path('logout/', views.logout_user, name="logout"),
    path('clinical/', views.clinical_dc_view, name='clinical'),
    path('cl_dc_dl/', views.cl_dc_dl_view, name='cl_dc_dl'),
    path('flash_tools/', views.flash_report_tools_view, name='flash_tools'),
    path("register", views.register_request, name="register"),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
         name='password_reset_complete'),
    path("password_reset", views.password_reset_request, name="password_reset")

]

BH_DJANGO/pages/models.py
from django.db import models

from django.contrib.auth.models import User

class Nurse(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Nurse = models.BooleanField(default=False,null=True, blank=True)

class Therapist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Therapist = models.BooleanField(default=False,null=True, blank=True)

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Admin = models.BooleanField(default=False,null=True, blank=True)

class Flash_User(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Flash = models.BooleanField(default=False,null=True, blank=True)

BH_DJANGO/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <title>BHC</title>
</head>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        {% load static %}
        <a class="navbar-brand" href="#"><img src="{% static 'logo.png' %}" alt="logo" width="100" height="60"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                {% if perms.pages.view_flash_user %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false"> Flash Report Tools </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                        <li class="nav-item dropdown">
                            <a class="dropdown-item" aria-current="page" href="{% url 'flash_tools' %}">Flash Report
                                Editor</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="dropdown-item" aria-current="page" href="{% url 'flash' %}">Flash Lookup</a>
                        </li> {% endif %}
                        </ul>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false"> Excel Analysis Tools </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    {% if perms.pages.view_nurse %}
                                <li class="nav-item dropdown">
                                    <a class="dropdown-item" aria-current="page" href="{% url 'viv' %}">Vivitrol
                                        Count</a>
                                </li>
                                {% endif %}
                                <li class="nav-item dropdown">{% if user.is_superuser %}
                                    <a class="dropdown-item" aria-current="page" href="{% url 'clinical' %}">Clinical DC
                                        Report</a>{% endif %}
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="#">More to come!</a></li>
                            </ul>
                        </li>
                    </ul>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false"> Hi, {{user.first_name}} </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        </li>
                        {% if user.is_superuser %}
                        <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a></li>
                        {% endif %}
                        {% if user.is_superuser %}
                        <li><a class="dropdown-item" href="{% url 'register' %}">New User</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<body>
{% block content %}
replace me
{% endblock %}
{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/gsap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/ScrollTrigger.min.js"></script>
<script type="text/javascript" src="{% static 'app.js' %}"></script>
{% endblock script %}
</body>
</html>

BH_DJANGO/templates/cl_dc_dl.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<body class="cl_rsults" style="background-image: url('{% static 'beach_img.jpg'%}');">
<div class="success_mess">
    <strong>
        Congratulations, data compiling was a success! Please click below to start download; download will appear in the bottom left corner.
    </strong>
</div>
<div>
    <form method="post"> {% csrf_token %}
        <ul class="cl_dl_dlink">
            <li>
                <u>Download the current months clinical discharge report data:</u>
                <input class="cl_dl_button" name="cl_dl" type="submit" value="Download">
            </li>
        </ul>
    </form>
</div>
</body>
{% endblock %}

BH_DJANGO/templates/clinical.html
{% extends 'base.html' %}
{% block content %}
<body>
<div class="clinical_DC_form"><strong>
    <h1 class="cl_head">Clinical Discharge Report Data Prep</h1>

    <form action="" method="post" enctype="multipart/form-data">

        {% csrf_token %}
        {{ form.as_p }}
        <input name="cl_analyze" class="btn btn-primary" type="submit" value="Analyze">

    </form>
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <p class="refresh"><a class="btn btn-primary" href="{% url 'clinical' %}">Refresh Page</a></p>
</strong>
</div>
</body>
{% endblock %}

BH_DJANGO/templates/clinical_dc.html
{% extends 'base.html' %}
{% block content %}
<body>
<div class="clinical_DC_form"><strong>
    <h1 class="cl_head">Clinical Discharge Report Data Prep</h1>
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <p class="refresh"><a class="btn btn-primary" href="{% url 'clinical' %}">Refresh Page</a></p>
</strong>
</div>
</body>
{% endblock %}

BH_DJANGO/templates/flash.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
<body class="flash_html">
<div class="flash_page">
    <div class="help1" style="grid-area: help">
        <ol class="instructions" start="1">
            <h2 class="in_header">
                <u>
                    Instructions
                </u>
            </h2>
            <li>
                Move the flash report from your email to the downloads section of your file explore
            </li>
            <li>
                From the downloads section in Kipu download the file called Flash Manual
            </li>
            <li>
                From the downloads section in Kipu download the file called Flash Manual
            </li>
            <li>
                Click choose file for <strong>Flash File</strong> and choose the previously downloaded Flash File
            </li>
            <li>
                Click choose file for <strong>Kipu File</strong> and choose the previously downloaded Kipu File
            </li>
            <li>
                Click <strong>Analyze</strong>
            </li>
        </ol>
    </div>
    <div class="f_logo" style="grid-area: logo">
        <img class="logo_img" src="{% static 'logo.png' %}" alt="logo">
    </div>
    <div class="flash_form" style="grid-area: form"><strong>
        <form action="" method="post" enctype="multipart/form-data">

            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" value="Analyze">
        </form>
    </strong>
    </div>
</div>
</body>


{% endblock %}

BH_DJANGO/templates/flash_return.html
 {% extends 'base.html' %}
 {% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>TableView - Startup</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2 class="text-center"><u>Patients Missing From Flash</u></h2><br>
  <table class="table table-primary table-striped">
    <caption>- patients that appear here may be missing from the flash report or have both their name and mrn listing incorrectly, if table is empty there are no missing patients</caption>
    <thead>
      <tr>
        <th>Name</th>
        <th>MR</th>
        <th>Sex</th>
        <th>Insurance</th>
        <th>Admission Date</th>
        <th>Length Of Stay</th>
        <th>Program</th>
        <th>Payment Method</th>
      </tr>
    </thead>
    <tbody>
    <!-- jinja2 Technique -->
    {% if d %}
    {% for i in d %}
      <tr>
        <td>{{i.Name}}</td>
        <td>{{i.MR}}</td>
        <td>{{i.Sex}}</td>
        <td>{{i.Insurance}}</td>
        <td>{{i.Admission}}</td>
        <td>{{i.LOS}}</td>
        <td>{{i.Program}}</td>
        <td>{{i.Payment}}</td>
      </tr>
    {% endfor %}
    {% endif %}
    </tbody>
  </table>
</div>
</body>
</html>
  {% endblock %}

BH_DJANGO/templates/flash_tools.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<body class="flash_tools" style="background-image: url('{% static 'beach_img.jpg'%}');">
<div class="fltool_grid">

    <form method="post"> {% csrf_token %}
        <div class="refresh_button" style="grid-area: instr">
            <ul>
                <h3>
                    <u>
                        Instructions for Flash Report
                    </u>
                </h3>
                <li>
                    Fill out the form to the right
                </li>
                <li>
                    <strong>
                        Make sure MRN is correct!!
                    </strong>
                </li>
                <li>
                    Click submit on the google form
                </li>
                <li>
                    Finally click the button below <strong>Only Once!</strong>
                </li>
                <li>
                    Power Bi report will be refreshed and sent to your email
                </li>
            </ul>
            <input name="report_refresh" class="btn btn-info" type="submit" value="Refresh Power BI Report">
        </div>
        <div class="dl_fl_changes" style="grid-area: dlb">
            <h3 style="text-align: center">Yesterday's Census Changes</h3>
            <form method="post"> {% csrf_token %}
                <table class="table table-Default table-hover table-bordered table-sm">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <caption class="home_dl">- <input class="btn btn-info" name="fl_changes" type="submit"
                                                          value="Download Full File">
                        </caption>
                        <thead>
                        <tr>
                            <th>Patient</th>
                            <th>Change</th>
                            <th>LOC Change</th>
                            <th>Commit LOS</th>
                        </tr>
                        </thead>
                        <tbody>
                        <!-- jinja2 Technique -->
                        {% if d %}
                        {% for i in d %}
                        <tr>
                            <td>{{i.Patient}}</td>
                            <td>{{i.Change}}</td>
                            <td>{{i.LOC_Change}}</td>
                            <td>{{i.Commit_LOS}}</td>
                        </tr>
                        {% endfor %}
                        {% endif %}
                        </tbody>
                </table>
            </form>
        </div>
    </form>
    <div class="flash_tools_div" style="grid-area: gform">
        <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeQIcLOVLmW6trL9m6mHRCFGu_4FPHcbM1nqks2_SzwTu2LsA/viewform?embedded=true"
                width="640" height="1100" frameborder="0" marginheight="0" marginwidth="0">Loading…
        </iframe>
    </div>
</div>
</body>
{% endblock %}

BH_DJANGO/templates/home.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<html lang="en">
<head>
    <title>TableView - Startup</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>
<body class="home" style="background-image: url('{% static 'beach_img.jpg'%}');">
<div style="max-width: 1500px; margin: 0 auto;">
    <div class="grid-template">
        <div style="grid-area: chart">
            <div class="container">
                <h2 class="text-center"><u>Beach House Main Analytics</u></h2><br>
                <table class="table table-Default table-hover table-bordered table-sm">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <caption class="home_dl"><input name="recent_ad" class="btn btn-primary" type="submit" value="Download"> - Recent
                            Admissions
                        </caption>
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>MR</th>
                            <th>Admit Date</th>
                            <th>Level of Care</th>
                            <th>Length Of Stay</th>
                            <th>Age</th>
                            <th>Gender</th>
                            <th>Drug of Choice</th>
                            <th>Therapist</th>
                            <th>Payment Method</th>
                        </tr>
                        </thead>
                        <tbody>
                        <!-- jinja2 Technique -->
                        {% if d %}
                        {% for i in d %}
                        <tr>
                            <td>{{i.Name}}</td>
                            <td>{{i.mr}}</td>
                            <td>{{i.admission_date}}</td>
                            <td>{{i.program_name}}</td>
                            <td>{{i.length_of_stay}}</td>
                            <td>{{i.age}}</td>
                            <td>{{i.sex}}</td>
                            <td>{{i.DOC}}</td>
                            <td>{{i.Therapist}}</td>
                            <td>{{i.paymentmethod}}</td>
                        </tr>
                        {% endfor %}
                        {% endif %}
                        </tbody>
                    </form>
                </table>
            </div>
        </div>
        <div class="grid-template">
            <div class="chart_2row" style="grid-area: Graph"> {{chart_LOC|safe}}</div>
            <div class="chart_2row" style="grid-area: Text">{{chart_G|safe}}</div>
            <div class="chart_1row" style="grid-area: bottom">{{chart_Age|safe}}</div>
            <div class="chart_3row" style="grid-area: rowthree">{{chart_DOC|safe}}</div>
            {% if perms.pages.view_therapist %}
            <div class="container2" style="grid-area: chart2">
                <table id="table2" class="table table-Default table-hover table-bordered table-sm">
                    <h2> Therapist Caseload</h2>
                    <caption class="therapist_caseload">
                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                        <input name="caseload" class="btn btn-primary" type="submit" value="Download"> - Caseload
                        </form>
                    </caption>
                    <thead>
                    <tr>
                        <th>Therapist</th>
                        <th>Patient Count</th>
                    </tr>
                    </thead>
                    <tbody>
                    <!-- jinja2 Technique -->
                    {% if d2 %}
                    {% for i in d2 %}
                    <tr>
                        <td>{{i.Therapist}}</td>
                        <td>{{i.Count_of_Patients}}</td>
                    </tr>
                    {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div> {% endif %}
        </div>
    </div>
</div>
</body>
</html>
{% endblock %}

BH_DJANGO/templates/login.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <title>LoginSystem</title>
</head>

<div>
    {% load static %}
    <img class="login_img" src="{% static '/logo.png' %}" alt="logo">
</div>
<div>
    <h1>Welcome to Beach House Analytics!!</h1>
</div>
<body class="login_body">
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <p><a href="/password_reset">Forgot Password?</a>!</p>
    <input type="submit" value="Login"/>

</form>
<p class="login_text">If you have been authorized to use this system and you do not have<br>
    login credentials please <a href="https://forms.office.com/pages/responsepage.aspx?id=oRE-s4024Eiw1DaBc2GOslEOMI0X1ylEkKi3wuQ8LG5UMk5LMlQ2MEVBNjJFVDI1UTZIRVNFQzVNMS4u" target="_blank">click here</a> to submit Help Desk <br>
    ticket
</p>
</body>
</html>

BH_DJANGO/templates/register_user.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}

{% load static %}
<body>
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="accounts/login/">login</a> instead.</p>
</div>
</body>
{% endblock %}

BH_DJANGO/templates/unsub.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% load static %}
<body>
<div style="font-size: 30px; text-align: center;">
Leopards never manage to escape from the zoo. They’re always spotted.<br>
<img class="login_img" src="{% static 'unsub.jpg' %}" alt="logo">
</div>
</body>
</html>

BH_DJANGO/templates/viv.html
{% extends 'base.html' %}

{% block content %}
<div class="viv_css">
    {% if messages %}
{% for message in messages %}
<div class="alert alert-success" role="alert">
    <strong>{{message|safe}}</strong>
</div>
{% endfor %}
{% endif %}
    <h2>Vivitrol Count Analyzer</h2>
<p>
    <font size="+1"><strong>Instructions on downloading file</strong><font>
<ul>
    <li>Go to the bottom of the 2nd page of the <strong>Public Reports</strong> in Kipu</li>
    <li>Click the pencil on the <strong>Vivitrol Injections</strong> report</li>
    <li>Update date range then scroll to the bottom and click <strong>Run Report</strong></li>
    <li>Click your initials in the top right and click downloads</li>
    <li><strong>Click download</strong> next to the Vivitrol Injections report</li>
    <li><a href="{% url 'viv_help' %}">Additional Help</a></li>


</ul>


</p>

<form action="" method="post" enctype="multipart/form-data"> {% csrf_token %}
    <div>
        {{ form.as_p }}
        <label for="sheet1" class="btn btn-secondary">Please choose "jdg-vivitrol" csv file</label></div>
    <p></p>
    <div>
        <button type="submit">Analyze File</button>
    </div>
</form>
</div>
{% endblock %}

BH_DJANGO/templates/viv_help.html
 {% extends 'base.html' %}

{% block content %}

 <div>
<h2 class="viv_help_css">Vivitrol Help</h1>
{% load static %}
     <img src="{% static 'Vivitrol_Help.gif' %}" alt="Vivitrol_Help">



  </div>








  {% endblock %}